# SwiftLint Configuration for ChoirHelper

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - .direnv
  - "**/.gitkeep"

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_comma
  - attributes  # Conflicts with swift-format's attribute placement
  - multiline_arguments  # Conflicts with swift-format's line wrapping
  - multiline_parameters  # Conflicts with swift-format's line wrapping
  - multiline_function_chains  # Conflicts with swift-format's line wrapping
  - opening_brace  # Conflicts with swift-format's brace placement on multi-line declarations
  - pattern_matching_keywords  # Conflicts with swift-format's binding style

# Rule configurations
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: false
  ignores_comments: false
  ignores_interpolated_strings: false
  ignores_urls: true

function_body_length:
  warning: 40
  error: 60

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - to
    - at
    - in
    - i
    # Musical note names (PitchStep enum)
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    # Musical dynamics (Dynamic enum)
    - p

force_unwrapping:
  severity: warning

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    message: "Use os.Logger instead of print"
    severity: warning

  no_nslog:
    name: "No NSLog statements"
    regex: "\\bNSLog\\("
    message: "Use os.Logger instead of NSLog"
    severity: warning

reporter: "xcode"
